//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAerolinea.WS_Aerolinea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Aerolinea.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Pasajero", ReplyAction="http://tempuri.org/IService/WS_PasajeroResponse")]
        string WS_Pasajero(int type, string _pasajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Pasajero", ReplyAction="http://tempuri.org/IService/WS_PasajeroResponse")]
        System.Threading.Tasks.Task<string> WS_PasajeroAsync(int type, string _pasajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Viaje", ReplyAction="http://tempuri.org/IService/WS_ViajeResponse")]
        string WS_Viaje(int type, string _viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Viaje", ReplyAction="http://tempuri.org/IService/WS_ViajeResponse")]
        System.Threading.Tasks.Task<string> WS_ViajeAsync(int type, string _viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_ServicioAdicional", ReplyAction="http://tempuri.org/IService/WS_ServicioAdicionalResponse")]
        string WS_ServicioAdicional(int type, string _servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_ServicioAdicional", ReplyAction="http://tempuri.org/IService/WS_ServicioAdicionalResponse")]
        System.Threading.Tasks.Task<string> WS_ServicioAdicionalAsync(int type, string _servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Maleta", ReplyAction="http://tempuri.org/IService/WS_MaletaResponse")]
        string WS_Maleta(int type, string _maleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Maleta", ReplyAction="http://tempuri.org/IService/WS_MaletaResponse")]
        System.Threading.Tasks.Task<string> WS_MaletaAsync(int type, string _maleta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebAerolinea.WS_Aerolinea.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebAerolinea.WS_Aerolinea.IService>, WebAerolinea.WS_Aerolinea.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WS_Pasajero(int type, string _pasajero) {
            return base.Channel.WS_Pasajero(type, _pasajero);
        }
        
        public System.Threading.Tasks.Task<string> WS_PasajeroAsync(int type, string _pasajero) {
            return base.Channel.WS_PasajeroAsync(type, _pasajero);
        }
        
        public string WS_Viaje(int type, string _viaje) {
            return base.Channel.WS_Viaje(type, _viaje);
        }
        
        public System.Threading.Tasks.Task<string> WS_ViajeAsync(int type, string _viaje) {
            return base.Channel.WS_ViajeAsync(type, _viaje);
        }
        
        public string WS_ServicioAdicional(int type, string _servicio) {
            return base.Channel.WS_ServicioAdicional(type, _servicio);
        }
        
        public System.Threading.Tasks.Task<string> WS_ServicioAdicionalAsync(int type, string _servicio) {
            return base.Channel.WS_ServicioAdicionalAsync(type, _servicio);
        }
        
        public string WS_Maleta(int type, string _maleta) {
            return base.Channel.WS_Maleta(type, _maleta);
        }
        
        public System.Threading.Tasks.Task<string> WS_MaletaAsync(int type, string _maleta) {
            return base.Channel.WS_MaletaAsync(type, _maleta);
        }
    }
}
