//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasServicio.WS_Aerolinea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Aerolinea.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Pasajero", ReplyAction="http://tempuri.org/IService/WS_PasajeroResponse")]
        object WS_Pasajero(int type, object _pasajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Pasajero", ReplyAction="http://tempuri.org/IService/WS_PasajeroResponse")]
        System.Threading.Tasks.Task<object> WS_PasajeroAsync(int type, object _pasajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Viaje", ReplyAction="http://tempuri.org/IService/WS_ViajeResponse")]
        object WS_Viaje(int type, object _viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Viaje", ReplyAction="http://tempuri.org/IService/WS_ViajeResponse")]
        System.Threading.Tasks.Task<object> WS_ViajeAsync(int type, object _viaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_ServicioAdicional", ReplyAction="http://tempuri.org/IService/WS_ServicioAdicionalResponse")]
        object WS_ServicioAdicional(int type, object _servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_ServicioAdicional", ReplyAction="http://tempuri.org/IService/WS_ServicioAdicionalResponse")]
        System.Threading.Tasks.Task<object> WS_ServicioAdicionalAsync(int type, object _servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Maleta", ReplyAction="http://tempuri.org/IService/WS_MaletaResponse")]
        object WS_Maleta(int type, object _maleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_Maleta", ReplyAction="http://tempuri.org/IService/WS_MaletaResponse")]
        System.Threading.Tasks.Task<object> WS_MaletaAsync(int type, object _maleta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PruebasServicio.WS_Aerolinea.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PruebasServicio.WS_Aerolinea.IService>, PruebasServicio.WS_Aerolinea.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object WS_Pasajero(int type, object _pasajero) {
            return base.Channel.WS_Pasajero(type, _pasajero);
        }
        
        public System.Threading.Tasks.Task<object> WS_PasajeroAsync(int type, object _pasajero) {
            return base.Channel.WS_PasajeroAsync(type, _pasajero);
        }
        
        public object WS_Viaje(int type, object _viaje) {
            return base.Channel.WS_Viaje(type, _viaje);
        }
        
        public System.Threading.Tasks.Task<object> WS_ViajeAsync(int type, object _viaje) {
            return base.Channel.WS_ViajeAsync(type, _viaje);
        }
        
        public object WS_ServicioAdicional(int type, object _servicio) {
            return base.Channel.WS_ServicioAdicional(type, _servicio);
        }
        
        public System.Threading.Tasks.Task<object> WS_ServicioAdicionalAsync(int type, object _servicio) {
            return base.Channel.WS_ServicioAdicionalAsync(type, _servicio);
        }
        
        public object WS_Maleta(int type, object _maleta) {
            return base.Channel.WS_Maleta(type, _maleta);
        }
        
        public System.Threading.Tasks.Task<object> WS_MaletaAsync(int type, object _maleta) {
            return base.Channel.WS_MaletaAsync(type, _maleta);
        }
    }
}
